### ISSUE TITLE
Django 1.11 support

### ISSUE THREAD

**Issue by lydell** [5monkeys/django-viewlet#37]
For now, this fork seems to work: https://github.com/propellerheads/django-viewlet/tree/5365092edca7b034e0822715fd484516c7f21949

**Comment by andreif** [comment]
I think it's the same as #36

**Comment by lydell** [comment]
It probably is! I somehow forgot to check the open PRs.

**Comment by beshrkayali** [comment]
I'm trying it now and it doesn't actually work. Mainly for use of deprecated `patterns`  https://github.com/propellerheads/django-viewlet/blob/65dff1166b7faf30763e11517932ab6b8348fcc2/viewlet/urls.py#L8,

**Comment by andreif** [comment]
Fixed in #39.
